/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DialogBox: typeof import('./src/components/DialogBox.vue')['default']
    DownloadButtons: typeof import('./src/components/DownloadButtons.vue')['default']
    EditorHeader: typeof import('./src/components/EditorHeader.vue')['default']
    GlyphAdder: typeof import('./src/components/GlyphManager/GlyphAdder.vue')['default']
    GlyphEditor: typeof import('./src/components/GlyphEditor.vue')['default']
    GlyphGrid: typeof import('./src/components/GlyphGrid.vue')['default']
    GlyphInfo: typeof import('./src/components/GlyphInfo.vue')['default']
    GlyphList: typeof import('./src/components/GlyphManager/GlyphList.vue')['default']
    GlyphManager: typeof import('./src/components/GlyphManager.vue')['default']
    HexCodeInput: typeof import('./src/components/HexCodeInput.vue')['default']
    IFa6BrandsGithub: typeof import('~icons/fa6-brands/github')['default']
    IMaterialSymbolsAddBoxOutline: typeof import('~icons/material-symbols/add-box-outline')['default']
    IMaterialSymbolsCheck: typeof import('~icons/material-symbols/check')['default']
    IMaterialSymbolsClose: typeof import('~icons/material-symbols/close')['default']
    IMaterialSymbolsContentCopy: typeof import('~icons/material-symbols/content-copy')['default']
    IMaterialSymbolsContentCopyOutline: typeof import('~icons/material-symbols/content-copy-outline')['default']
    IMaterialSymbolsContentCut: typeof import('~icons/material-symbols/content-cut')['default']
    IMaterialSymbolsContentPaste: typeof import('~icons/material-symbols/content-paste')['default']
    IMaterialSymbolsDarkMode: typeof import('~icons/material-symbols/dark-mode')['default']
    IMaterialSymbolsDeleteOutline: typeof import('~icons/material-symbols/delete-outline')['default']
    IMaterialSymbolsDownload: typeof import('~icons/material-symbols/download')['default']
    IMaterialSymbolsDrawOutline: typeof import('~icons/material-symbols/draw-outline')['default']
    IMaterialSymbolsEditOutline: typeof import('~icons/material-symbols/edit-outline')['default']
    IMaterialSymbolsFileDownload: typeof import('~icons/material-symbols/file-download')['default']
    IMaterialSymbolsGlyphs: typeof import('~icons/material-symbols/glyphs')['default']
    IMaterialSymbolsImageOutline: typeof import('~icons/material-symbols/image-outline')['default']
    IMaterialSymbolsInfoOutline: typeof import('~icons/material-symbols/info-outline')['default']
    IMaterialSymbolsInkEraserOutline: typeof import('~icons/material-symbols/ink-eraser-outline')['default']
    IMaterialSymbolsLightMode: typeof import('~icons/material-symbols/light-mode')['default']
    IMaterialSymbolsMopOutline: typeof import('~icons/material-symbols/mop-outline')['default']
    IMaterialSymbolsRedo: typeof import('~icons/material-symbols/redo')['default']
    IMaterialSymbolsSelect: typeof import('~icons/material-symbols/select')['default']
    IMaterialSymbolsSettings: typeof import('~icons/material-symbols/settings')['default']
    IMaterialSymbolsSyncOutline: typeof import('~icons/material-symbols/sync-outline')['default']
    IMaterialSymbolsUndo: typeof import('~icons/material-symbols/undo')['default']
    IMaterialSymbolsUploadFileOutline: typeof import('~icons/material-symbols/upload-file-outline')['default']
    PixelPreview: typeof import('./src/components/GlyphManager/PixelPreview.vue')['default']
    SearchToolbar: typeof import('./src/components/GlyphManager/SearchToolbar.vue')['default']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
    ToolButtons: typeof import('./src/components/ToolButtons.vue')['default']
    UploadSection: typeof import('./src/components/GlyphManager/UploadSection.vue')['default']
  }
}
